git:
  autoFetch: false
# If true, show a confirmation popup before quitting Lazygit
confirmOnQuit: true
# If true, exit Lazygit when the user presses escape in a context where there is
# nothing to cancel/close
quitOnTopLevelReturn: true

keybinding:
  universal:
    quit: <esc>


customCommands:
  - key: 'E'
    description: 'Add empty commit'
    context: 'commits'
    command: 'git commit --allow-empty -m "empty commit"'
    loadingText: 'Committing empty commit...'
